mylist = ["khana","pina", "sona" ,"padhna", "design","code" ]
print(mylist)
mylist.sort()
print(mylist)

#order
print(mylist[3])

numbers =[1,4,6,8,0,11,17,15]
numberlist = sorted(numbers)

print(numberlist)
numbers.reverse()
print(numbers)

print(len(numbers))
print(type(numbers))
print(numbers[-1:6:-3])
numbers.append(21)
numbers.append(17)
numbers.append(60)
numbers.insert(3,37)
numbers.remove(6)
numbers.pop()
print(numbers)




newlist = [21, 28, 56, 78, 50, 48, 38,]
newlist.sort()
newlist.reverse()
newlist.append(20)
newlist.remove(56)
#newlist.pop()
newlist.insert(5, 66)
#newlist.count()
newlist.__len__()
print(newlist)
'''newlist
newlist
newlist
newlist'''